import type { Metadata } from "next";
import 'bulma/css/bulma.css'
import '@/components/common/loader/loader.css'
import { SessionProvider } from "next-auth/react";


export const metadata: Metadata = {
  title: "Receitas App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
